spring.application.name=processor-service
spring.datasource.url=jdbc:postgresql://localhost:5432/predictions_processor
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.main.allow-bean-definition-overriding=true

sensor.processor.id=SENSOR_PROCESSOR_1

server.port=10000