/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_sensordataprocessor_service_DataService */

#ifndef _Included_tech_noetzold_processor_service_service_DataService
#define _Included_tech_noetzold_processor_service_service_DataService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_sensordataprocessor_service_DataService
 * Method:    filterData
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_tech_noetzold_processor_service_service_DataService_filterData
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     com_example_sensordataprocessor_service_DataService
 * Method:    compressData
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_tech_noetzold_processor_service_service_DataService_compressData
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     com_example_sensordataprocessor_service_DataService
 * Method:    aggregateData
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_tech_noetzold_processor_service_service_DataService_aggregateData
  (JNIEnv *, jobject, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
