# Usando a imagem oficial do RabbitMQ com o plugin de gestão
FROM rabbitmq:3-management

# Configuração do RabbitMQ (opcional, já que estamos usando a imagem padrão)
ENV RABBITMQ_DEFAULT_USER=guest
ENV RABBITMQ_DEFAULT_PASS=guest
