spring.application.name=Capture-service

spring.rabbitmq.host=172.17.0.3
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.virtual-host=/

sensor.processor.id=${sensor.processor.id:SENSOR_PROCESSOR_DEFAULT}

server.port=9000