spring.application.name=data-handler
spring.datasource.url=jdbc:postgresql://db:5432/simulator
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
