spring.application.name=config-service
spring.datasource.url=jdbc:postgresql://localhost:5432/config_service
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


# URL do serviço de predição
prediction-service.url=http://localhost:8000

server.port=8060